/*
 * This program source code file is part of KiChad, a Codex-integrated downstream of KiCad.
 *
 * Copyright (C) 2026 KiChad Developers
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 */

#include <boost/test/unit_test.hpp>

#include <kicad/codex/fabrication_artifact_validator.h>

#include <filesystem>
#include <fstream>

#include <kiid.h>
#include <nlohmann/json.hpp>
#include <wx/filename.h>


namespace
{

using JSON = nlohmann::json;


class ARTIFACT_FIXTURE
{
public:
    ARTIFACT_FIXTURE()
    {
        m_root = std::filesystem::path( wxFileName::GetTempDir().ToStdString() )
                 / ( "kichad-artifact-validator-" + KIID().AsString().ToStdString() );
        std::filesystem::create_directories( m_root );
    }

    ~ARTIFACT_FIXTURE()
    {
        std::error_code ignored;
        std::filesystem::remove_all( m_root, ignored );
    }

    std::filesystem::path Write( const std::string& aName, const std::string& aSource )
    {
        const std::filesystem::path path = m_root / aName;
        std::ofstream output( path, std::ios::binary | std::ios::trunc );
        output.write( aSource.data(), static_cast<std::streamsize>( aSource.size() ) );
        output.close();
        BOOST_REQUIRE( output.good() );
        return path;
    }

private:
    std::filesystem::path m_root;
};


JSON boardStatistics()
{
    return {
        { "metadata",
          { { "date", "2026-07-19T00:00:00" },
            { "generator", "KiCad 10.0.4-KiChad" },
            { "project", "controller" }, { "board_name", "controller" } } },
        { "board",
          { { "has_outline", true }, { "width", "10.0000 mm" },
            { "height", "10.0000 mm" }, { "area", "100.000 mm²" },
            { "board_thickness", "1.6000 mm" } } },
        { "pads",
          { { "through_hole", 0 }, { "smd", 8 }, { "connector", 0 },
            { "npth", 0 }, { "castellated", 0 }, { "press_fit", 0 } } },
        { "vias", { { "through", 2 }, { "blind", 0 }, { "buried", 0 },
                    { "micro", 0 } } },
        { "components",
          { { "tht", { { "front", 0 }, { "back", 0 }, { "total", 0 } } },
            { "smd", { { "front", 1 }, { "back", 1 }, { "total", 2 } } },
            { "unspecified", { { "front", 0 }, { "back", 0 }, { "total", 0 } } },
            { "total", { { "front", 1 }, { "back", 1 }, { "total", 2 } } } } },
        { "drill_holes",
          JSON::array( { { { "count", 2 }, { "shape", "Round" },
                           { "x_size", "0.3000 mm" }, { "y_size", "0.3000 mm" },
                           { "plated", true }, { "source", "Via" },
                           { "start_layer", "F.Cu" }, { "stop_layer", "B.Cu" } } } ) }
    };
}

} // namespace


BOOST_AUTO_TEST_SUITE( FabricationArtifactValidator )


BOOST_AUTO_TEST_CASE( AcceptsNativeAssemblySvgAndRejectsActiveContent )
{
    ARTIFACT_FIXTURE fixture;
    const std::string valid =
            "<?xml version=\"1.0\"?>\n"
            "<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" "
            "width=\"10mm\" height=\"10mm\" viewBox=\"0 0 10 10\">"
            "<desc>Image generated by PCBNEW</desc><path d=\"M0 0 L10 10\"/></svg>\n";
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateAssemblySvg(
                    fixture.Write( "valid.svg", valid ), error ),
            error );

    error.clear();
    const std::string active = valid.substr( 0, valid.find( "</svg>" ) )
                               + "<script>alert(1)</script></svg>\n";
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateAssemblySvg(
            fixture.Write( "active.svg", active ), error ) );
    BOOST_CHECK_NE( error.find( "active content" ), std::string::npos );
}


BOOST_AUTO_TEST_CASE( AcceptsStructuredAsciiDxfAndRejectsTruncation )
{
    ARTIFACT_FIXTURE fixture;
    const std::string valid =
            "  0\nSECTION\n  2\nHEADER\n  0\nENDSEC\n"
            "  0\nSECTION\n  2\nENTITIES\n  0\nLINE\n"
            " 10\n0\n 20\n0\n 11\n1\n 21\n1\n"
            "  0\nENDSEC\n  0\nEOF\n";
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateAssemblyDxf(
                    fixture.Write( "valid.dxf", valid ), error ),
            error );

    error.clear();
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateAssemblyDxf(
            fixture.Write( "truncated.dxf", valid.substr( 0, valid.size() - 8 ) ), error ) );
    BOOST_CHECK( !error.empty() );
}


BOOST_AUTO_TEST_CASE( AcceptsSectionedGenCadAndRejectsMismatchedSections )
{
    ARTIFACT_FIXTURE fixture;
    const std::string valid =
            "$HEADER\nGENCAD 1.4\n$ENDHEADER\n"
            "$BOARD\nLINE 0 0 1 0\n$ENDBOARD\n"
            "$COMPONENTS\n$ENDCOMPONENTS\n"
            "$SIGNALS\n$ENDSIGNALS\n"
            "$TRACKS\n$ENDTRACKS\n"
            "$ROUTES\n$ENDROUTES\n";
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateGenCad(
                    fixture.Write( "valid.cad", valid ), error ),
            error );

    error.clear();
    std::string mismatched = valid;
    mismatched.replace( mismatched.find( "$ENDBOARD" ), 9, "$ENDPADS" );
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateGenCad(
            fixture.Write( "mismatched.cad", mismatched ), error ) );
    BOOST_CHECK_NE( error.find( "mismatched" ), std::string::npos );
}


BOOST_AUTO_TEST_CASE( AcceptsBalancedVrmlAndRejectsBrokenGeometry )
{
    ARTIFACT_FIXTURE fixture;
    const std::string valid =
            "#VRML V2.0 utf8\n"
            "Transform { children [ Shape { geometry IndexedFaceSet { "
            "coord Coordinate { point [ 0 0 0, 1 0 0, 0 1 0 ] } "
            "coordIndex [ 0, 1, 2, -1 ] } } ] }\n";
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateVrml(
                    fixture.Write( "valid.wrl", valid ), error ),
            error );

    error.clear();
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateVrml(
            fixture.Write( "broken.wrl", valid.substr( 0, valid.size() - 3 ) ), error ) );
    BOOST_CHECK( !error.empty() );
}


BOOST_AUTO_TEST_CASE( AcceptsTypedBoardStatisticsAndRejectsWrongIdentity )
{
    ARTIFACT_FIXTURE fixture;
    const JSON valid = boardStatistics();
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateBoardStatistics(
                    fixture.Write( "valid.json", valid.dump( 2 ) + "\n" ),
                    "controller", error ),
            error );

    error.clear();
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateBoardStatistics(
            fixture.Write( "wrong.json", valid.dump( 2 ) + "\n" ),
            "different-board", error ) );
    BOOST_CHECK_NE( error.find( "planned board" ), std::string::npos );
}


BOOST_AUTO_TEST_CASE( AcceptsExactKiCadNetlistAndRejectsConnectivityDrift )
{
    ARTIFACT_FIXTURE fixture;
    const JSON plan = {
        { "fileStem", "controller" },
        { "expectedNetlistReferences", JSON::array( { "R1", "R2" } ) },
        { "expectedNetlistNoConnects", JSON::array() },
        { "expectedNetlistNets",
          JSON::array(
                  { { { "name", "SIGNAL" },
                      { "nodes",
                        JSON::array(
                                { { { "reference", "R1" }, { "pin", "1" } },
                                  { { "reference", "R2" }, { "pin", "1" } } } ) } } } ) }
    };
    const std::string valid =
            "(export (version \"E\")"
            " (design (source \"controller.kicad_sch\")"
            " (tool \"Eeschema 10.0.4-KiChad\"))"
            " (components (comp (ref \"R1\")) (comp (ref \"R2\")))"
            " (nets (net (code \"1\") (name \"SIGNAL\")"
            " (node (ref \"R1\") (pin \"1\"))"
            " (node (ref \"R2\") (pin \"1\")))))\n";
    std::string error;
    BOOST_CHECK_MESSAGE(
            KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateKiCadNetlist(
                    fixture.Write( "valid.net", valid ), plan, error ),
            error );

    error.clear();
    std::string missingComponent = valid;
    const std::string componentRecord = "(comp (ref \"R2\"))";
    const size_t componentPosition = missingComponent.find( componentRecord );
    BOOST_REQUIRE_NE( componentPosition, std::string::npos );
    missingComponent.erase( componentPosition, componentRecord.size() );
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateKiCadNetlist(
            fixture.Write( "missing-component.net", missingComponent ), plan, error ) );
    BOOST_CHECK_NE( error.find( "expected 2, native 1" ), std::string::npos );
    BOOST_CHECK_NE( error.find( "missing from native export: R2" ), std::string::npos );

    error.clear();
    std::string drifted = valid;
    const size_t secondReference = drifted.rfind( "(ref \"R2\")" );
    BOOST_REQUIRE_NE( secondReference, std::string::npos );
    drifted.replace( secondReference, std::string( "(ref \"R2\")" ).size(),
                     "(ref \"R1\")" );
    BOOST_CHECK( !KICHAD::FABRICATION_ARTIFACT_VALIDATOR::ValidateKiCadNetlist(
            fixture.Write( "drifted.net", drifted ), plan, error ) );
    BOOST_CHECK( !error.empty() );
}


BOOST_AUTO_TEST_SUITE_END()
